#!/usr/bin/env python3
# Copyright 2021 ETH Zurich and the OptArena authors.
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate tests/e2e_known_failures.txt for tests/test_e2e_numerical.py.

Runs the full foundation + HPC numerical sweep at S and records every
``<stem>::<backend>`` pair that currently FAILs (not ``ok``, not ``skip:*``).
Those pairs are the xfail allowlist the e2e gate tolerates while the translator
work lands. Run after a batch of translator fixes to prune pairs that now pass,
from the repo root::

    python -m tests.gen_e2e_known_failures
"""
from optarena.spec import KERNELS, BenchSpec
from tests.numerical_oracle import run_kernel
from tests.test_e2e_numerical import E2E_BACKENDS, _KNOWN_FAIL_FILE


def main():
    fails = []
    stems = []
    for key in sorted(KERNELS):
        stem = key.rsplit("/", 1)[-1]
        try:
            spec = BenchSpec.load(stem)
        except Exception:  # noqa: BLE001
            continue
        if spec.track in ("foundation", "hpc"):
            stems.append(stem)
    for i, stem in enumerate(stems):
        try:
            # pluto is opt-in in run_kernel; request the full gated set explicitly so
            # its FAIL pairs are recorded (matches how test_e2e_numerical calls it).
            res = run_kernel(stem, "S", only_backends=frozenset(E2E_BACKENDS))
        except Exception as exc:  # noqa: BLE001
            res = {b: f"FAIL:{type(exc).__name__}" for b in E2E_BACKENDS}
        for backend in E2E_BACKENDS:
            st = res.get(backend, "")
            if st.startswith("FAIL"):
                fails.append(f"{stem}::{backend}")
        print(f"[{i + 1}/{len(stems)}] {stem}", flush=True)
    header = ("# Auto-generated by `python -m tests.gen_e2e_known_failures` -- pairs that\n"
              "# currently FAIL the e2e gate (xfail-tolerated). Regenerate after\n"
              "# translator fixes to prune pairs that now pass.\n")
    _KNOWN_FAIL_FILE.write_text(header + "\n".join(sorted(fails)) + "\n")
    print(f"wrote {len(fails)} known-failing pairs to {_KNOWN_FAIL_FILE}")


if __name__ == "__main__":
    main()
