"""Emit a Pythran-AOT version of a numpy kernel.

Pythran reads a magic ``#pythran export <funcname>(<argtypes>)``
comment at the top of the file to know how to AOT-compile it. We
synthesise that comment from the IR's parameter table (which carries
shape + dtype for every array and the int type for symbols).
"""

from typing import List

from numpyto_c.ir import ArrayDesc, KernelIR

_DTYPE_TO_PYTHRAN: dict = {
    "float64": "float64",
    "float32": "float32",
    "float16": "float16",
    "complex128": "complex128",
    "complex64": "complex64",
    "int64": "int64",
    "int32": "int32",
    "int": "int",
    "int16": "int16",
    "int8": "int8",
    "uint64": "uint64",
    "uint32": "uint32",
    "uint16": "uint16",
    "uint8": "uint8",
    "bool": "bool",
    "bool_": "bool",
}


def _pythran_array_type(arr: ArrayDesc) -> str:
    """Render one Pythran array type, e.g. ``float64[:,:]``."""
    base = _DTYPE_TO_PYTHRAN.get(arr.dtype, "float64")
    bracket = "[" + ",".join(":" for _ in arr.shape) + "]"
    return f"{base}{bracket}"


def emit_pythran(numpy_source: str, kir: KernelIR) -> str:
    """Translate one numpy kernel source into its Pythran sibling.

    :param numpy_source: contents of ``<short>_numpy.py``.
    :param kir: parsed :class:`numpyto_c.ir.KernelIR` (used to build
        the ``#pythran export`` argument-type list).
    :returns: Python source with the ``#pythran export`` magic
        comment prepended.
    """
    # Expand ops pythran cannot template-instantiate verbatim (batched >=3-D
    # ``@``) into plain loops; a no-op for kernels that do not use them.
    from numpyto_common.numpy_desugar import desugar_for_python_backend
    numpy_source = desugar_for_python_backend(numpy_source, kir)

    sym_by_name = {s.name: s for s in kir.symbols}
    arr_by_name = {a.name: a for a in kir.arrays}
    sca_by_name = {s.name: s for s in kir.scalars}

    # The export types must be in the kernel's *verbatim def signature* order --
    # ``input_args`` -- NOT ``param_order()`` (the alphabetical-then-scalars ABI
    # order the C/Fortran bindings reorder into). Pythran compiles the body as-is,
    # so the i-th export type binds to the i-th def parameter; ABI order would land
    # types on the wrong params (e.g. fft_3d's scalar ``niter`` typed as an array).
    types: List[str] = []
    for arg in kir.input_args:
        if arg in sym_by_name:
            types.append("int")
        elif arg in arr_by_name:
            types.append(_pythran_array_type(arr_by_name[arg]))
        elif arg in sca_by_name:
            types.append(_DTYPE_TO_PYTHRAN.get(sca_by_name[arg].dtype, "float64"))
    export = f"#pythran export {kir.kernel_name}({', '.join(types)})\n"
    header = ('"""Auto-generated by NumpyToPythran. ``#pythran export`` declaration '
              'synthesised from bench_info; body preserved verbatim."""\n')
    return header + export + numpy_source
