"""Emit a Numba-compiled version of a numpy kernel.

Numba supports a large subset of numpy plus pure-Python loops; the
translation is simply wrapping the function in ``@numba.njit`` or
``@numba.njit(parallel=True)`` and leaving the body alone.

The ``parallel=True`` variant additionally rewrites bare ``range``
calls to ``numba.prange`` so loop-level parallelism is opt-in.
"""

import re
from typing import Literal

Flavor = Literal["njit", "njit_parallel"]

#: Per-flavor njit options (besides ``fastmath``, which is opt-in below).
#: ``fastmath`` is OFF by default: it lets LLVM reassociate reductions and
#: assume no-nan/no-inf, which diverges from numpy's exact semantics (so a
#: faithful translation must not enable it) and additionally miscompiles
#: some gather/while-loop reductions into a SIGSEGV on numba 0.65 + LLVM.
#: Pass ``fastmath=True`` to opt back into the perf-oriented flavor.
_BASE_OPTS = {
    "njit": [],
    "njit_parallel": ["parallel=True"],
}


def emit_numba(numpy_source: str, flavor: Flavor = "njit", fastmath: bool = False, kir=None) -> str:
    """Translate one numpy kernel source into its Numba sibling.

    :param numpy_source: contents of ``<short>_numpy.py``.
    :param flavor: ``"njit"`` for serial, ``"njit_parallel"`` for the
        parallel variant (rewrites bare ``range`` to ``nb.prange``).
    :param fastmath: opt into ``fastmath=True`` (off by default; see
        ``_BASE_OPTS`` for why faithful translation leaves it off).
    :param kir: parsed :class:`KernelIR`; when supplied, ops numba cannot
        type verbatim (batched >=3-D ``@``) are desugared into plain loops.
    :returns: Python source code.
    """
    if flavor not in _BASE_OPTS:
        raise ValueError(f"unknown numba flavor: {flavor!r}")
    if kir is not None:
        from numpyto_common.numpy_desugar import desugar_for_python_backend
        numpy_source = desugar_for_python_backend(numpy_source, kir, backend="numba")
    opts = list(_BASE_OPTS[flavor])
    if fastmath:
        opts.append("fastmath=True")
    opts.append("cache=True")
    decorator = f"@nb.njit({', '.join(opts)})"

    # 1. Make sure ``import numba as nb`` is present.
    out = numpy_source
    if "import numba" not in out:
        out = "import numba as nb\n" + out

    # 2. Inject the decorator on the first ``def`` line.
    out = re.sub(r"(?m)^(def\s+\w+\()", f"{decorator}\n\\1", out, count=1)

    # 3. Parallel flavor rewrites ``range`` to ``nb.prange`` (only the
    #    outermost call we see; we leave inner loops alone since
    #    nested prange tends to underperform).
    if flavor == "njit_parallel":
        out = re.sub(r"\bfor\s+(\w+)\s+in\s+range\(", r"for \1 in nb.prange(", out, count=1)

    header = (f'"""Auto-generated by NumpyToNumba ({flavor}). Decorator added; '
              f'body preserved verbatim."""\n')
    return header + out
