"""Emit a cupy version of a numpy-style kernel.

Every numpy reference is rebound to the SAME cupy alias ``cp``:

* ``import numpy as np`` -> ``import cupy as cp``
* ``import numpy``       -> ``import cupy as cp``  (no bare ``import cupy``)
* ``np.`` references     -> ``cp.``
* ``numpy.`` references  -> ``cp.``

The two ``numpy.`` cases MUST agree: the old emitter rewrote
``import numpy`` (no alias) to ``import cupy as cp`` but rewrote bare
``numpy.`` refs to ``cupy.`` -- so only ``cp`` was bound and every
``cupy.foo`` call raised ``NameError`` at runtime. Binding everything to
``cp`` fixes that (string-level replace; safe because the kernel body in
the Foundation corpus never quotes ``np.`` / ``numpy.`` inside a string
literal -- the surrounding test infrastructure lives outside the kernel).

RNG caveat: ``np.random`` maps to ``cp.random`` via the ``np.`` rewrite,
so ``np.random.seed(...)`` becomes ``cp.random.seed(...)`` and the kernel
stays DETERMINISTIC. But cuRAND is a different generator from numpy's
Mersenne Twister, so a kernel that consumes ``np.random.*`` values is NOT
bit-exact with the numpy reference even under the same seed -- that is a
device-RNG limitation, not a translation bug. The seed is the only bridge
available without reimplementing numpy's RNG on the GPU.

The resulting module exposes the same kernel function name, so the
HPCAgent-Bench harness picks it up unchanged via the legacy framework
dispatcher's ``<kernel>_<postfix>`` lookup.
"""

import re

#: Module-level rewrites applied in order. The ``\b`` anchors guard
#: against partial matches (e.g. ``snap_np_foo``). ``import numpy as np``
#: must precede ``import numpy`` so the aliased form is consumed first.
_SUBS = [
    (re.compile(r"\bimport numpy as np\b"), "import cupy as cp"),
    (re.compile(r"\bimport numpy\b"), "import cupy as cp"),
    (re.compile(r"\bnp\."), "cp."),
    (re.compile(r"\bnumpy\."), "cp."),
]


def emit_cupy(numpy_source: str) -> str:
    """Translate one numpy kernel source into its cupy sibling."""
    out = numpy_source
    for pattern, repl in _SUBS:
        out = pattern.sub(repl, out)
    header = ('"""Auto-generated by NumpyToCuPy. Cupy is a drop-in for numpy on '
              'GPU; the kernel body is left intact, numpy refs rebound to ``cp``."""\n')
    return header + out
