"""Emit a cupy version of a numpy-style kernel.

Two minimal substitutions:

* ``import numpy as np`` -> ``import cupy as cp``
* ``np.`` references -> ``cp.`` (string-level replace; safe because
  the kernel body in the Foundation corpus never quotes ``np.``
  inside a string literal -- the surrounding test infrastructure
  lives outside the kernel file).

The resulting module exposes the same kernel function name, so the
OptArena harness picks it up unchanged via the legacy framework
dispatcher's ``<kernel>_<postfix>`` lookup.
"""

import re

#: Module-level rewrites applied in order. The ``\b`` anchors guard
#: against partial matches (e.g. ``snap_np_foo``).
_SUBS = [
    (re.compile(r"\bimport numpy as np\b"), "import cupy as cp"),
    (re.compile(r"\bimport numpy\b"), "import cupy as cp"),
    (re.compile(r"\bnp\."), "cp."),
    (re.compile(r"\bnumpy\."), "cupy."),
]


def emit_cupy(numpy_source: str) -> str:
    """Translate one numpy kernel source into its cupy sibling."""
    out = numpy_source
    for pattern, repl in _SUBS:
        out = pattern.sub(repl, out)
    header = (
        '"""Auto-generated by NumpyToCuPy. Cupy is a drop-in for numpy on '
        'GPU; the kernel body is left intact, only ``np.`` -> ``cp.``."""\n'
    )
    return header + out
